# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-28 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcode', models.CharField(max_length=10, unique=True)),
                ('pdesc', models.TextField()),
                ('author', models.CharField(max_length=20)),
                ('is_done', models.BooleanField(default=False)),
                ('answer', models.FileField(default='', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stime', models.DateTimeField()),
                ('etime', models.DateTimeField()),
            ],
        ),
    ]
