# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-28 08:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('judge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='test_input',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='problem',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
