# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-28 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0002_auto_20170128_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='pname',
            field=models.CharField(default='', max_length=20),
        ),
    ]
