# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-28 10:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0003_problem_pname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='user',
        ),
    ]
