# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-28 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0005_problem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='pcode',
            field=models.IntegerField(),
        ),
    ]
