# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 23:43
from __future__ import unicode_literals

from django.db import migrations, models
import judge.models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0009_problem_user'),
    ]

    
