# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0010_auto_20170128_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='test_input',
            field=models.FileField(upload_to=b''),
        ),
    ]
