# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 04:52
from __future__ import unicode_literals

from django.db import migrations, models
import judge.models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0011_auto_20170129_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='answer',
            field=models.FileField(upload_to=judge.models.problem_pans),
        ),
        migrations.AlterField(
            model_name='problem',
            name='test_input',
            field=models.FileField(upload_to=judge.models.problem_pinp),
        ),
        migrations.AlterField(
            model_name='submission',
            name='upload',
            field=models.FileField(upload_to=judge.models.submission_code),
        ),
    ]
